services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apihub
    ports:
      - "3306:3306"
    volumes:
      - ./infra/mysql:/docker-entrypoint-initdb.d
