services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apihub
    ports:
      - "3306:3306"
    volumes:
      - apihub-mysql-data:/var/lib/mysql

volumes:
  apihub-mysql-data:
