"use client";

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type PropsWithChildren
} from "react";

export type AppLocale = "zh-CN" | "en-US";
export type ThemePreference = "system" | "dark" | "light";
export type ResolvedTheme = "dark" | "light";

const LOCALE_STORAGE_KEY = "apihub.locale";
const THEME_STORAGE_KEY = "apihub.theme";

type TranslationValues = Record<string, string | number>;
type TranslationCatalog = Record<string, string>;

const messages: Record<AppLocale, TranslationCatalog> = {
  "en-US": {
    "catalog.createProject": "Create project",
    "catalog.consoleBadge": "Group-first",
    "catalog.empty": "No matching projects. Adjust the search query or project group.",
    "catalog.emptyAll": "No workspaces yet",
    "catalog.emptyAllDetail":
      "Create the first project to start shaping grouped endpoints, debug policies, and mock runtime snapshots.",
    "catalog.group.all": "All projects",
    "catalog.group.all.description": "Browse every workspace you can access in this console.",
    "catalog.group.editable": "Editable",
    "catalog.group.editable.description": "Projects where you can shape APIs and runtime behavior.",
    "catalog.group.manage": "Manage members",
    "catalog.group.manage.description": "Projects where you can rebalance collaborators and ownership.",
    "catalog.group.review": "Review only",
    "catalog.group.review.description": "Read-only workspaces for review, browsing, and verification.",
    "catalog.heading": "Project command center",
    "catalog.heroDetail":
      "Start from a project group, then move into the exact workspace you want to edit, review, or govern.",
    "catalog.activeGroup": "Active group",
    "catalog.visibleProjects": "Visible projects",
    "catalog.filteredBy": "Filtered by \"{query}\"",
    "catalog.ready": "Ready to open the next workspace.",
    "catalog.loading": "Loading projects...",
    "catalog.search": "Search projects",
    "catalog.searchPlaceholder": "Search by project name, key, or description",
    "catalog.subtitle": "Choose a group first, then open the right API workspace.",
    "catalog.title": "Projects",
    "catalog.inventoryEyebrow": "Inventory",
    "catalog.inventoryTitle": "Projects in {group}",
    "catalog.inventoryDetail": "{count} workspaces ready for the next step.",
    "catalog.radarEyebrow": "Priority lanes",
    "catalog.radarTitle": "Project radar",
    "catalog.radarDetail":
      "Stay in the group-first flow, then jump straight into the workspaces with the highest ownership and runtime signal.",
    "catalog.radarScope": "Scope: {group}",
    "catalog.radarVisibleCount": "{count} projects in view",
    "catalog.radarEmpty": "No projects are visible in this lane yet.",
    "catalog.radar.manage": "Governance",
    "catalog.radar.writable": "Writable",
    "catalog.radar.review": "Review",
    "catalog.pulseEyebrow": "Operations",
    "catalog.pulseTitle": "Operations pulse",
    "catalog.pulseDetail":
      "A compact readout for group coverage, ownership pressure, and runtime safety before you step into a specific workspace.",
    "catalog.pulse.groups": "Project groups",
    "catalog.pulse.writable": "Writable lanes",
    "catalog.pulse.governance": "Governance seats",
    "catalog.pulse.debugRules": "Debug rules",
    "catalog.pulse.coverageLabel": "Writable coverage",
    "catalog.pulse.coverageDetail": "{editable} of {total} projects can be edited in the current inventory.",
    "catalog.createDrawer.closeOverlay": "Close create project overlay",
    "catalog.createDrawer.closePanel": "Close project creation panel",
    "catalog.createDrawer.eyebrow": "New workspace",
    "catalog.createDrawer.title": "Create project",
    "catalog.createDrawer.detail":
      "Start a fresh API workspace with a clean key, a first owner seat, and an empty debug policy baseline.",
    "catalog.createDrawer.close": "Close",
    "catalog.createDrawer.preview": "Live preview",
    "catalog.createDrawer.projectKeyFallback": "project-key",
    "catalog.createDrawer.projectName": "Project name",
    "catalog.createDrawer.projectKey": "Project key",
    "catalog.createDrawer.projectDescription": "Project description",
    "catalog.createDrawer.namePlaceholder": "Billing Hub",
    "catalog.createDrawer.keyPlaceholder": "billing-hub",
    "catalog.createDrawer.descriptionPlaceholder": "Billing APIs, reconciliation flows, and settlement webhooks.",
    "catalog.createDrawer.submit": "Create workspace",
    "catalog.createDrawer.submitting": "Creating...",
    "catalog.createDrawer.error.nameRequired": "Project name is required.",
    "catalog.createDrawer.error.keyRequired": "Project key is required.",
    "catalog.createDrawer.error.keyFormat": "Use lowercase letters, digits, and hyphens only.",
    "catalog.createDrawer.error.descriptionTooLong": "Keep the description within 280 characters.",
    "contract.example": "Example: {value}",
    "contract.fields": "{count} documented field",
    "contract.fields_plural": "{count} documented fields",
    "contract.noDescription": "No field description.",
    "contract.optional": "Optional",
    "contract.parametersDetail":
      "Inspect the request shape grouped by transport location so integration consumers can scan the contract quickly.",
    "contract.parametersEmpty": "No request parameters were documented for this endpoint.",
    "contract.parametersEyebrow": "Request contract",
    "contract.parametersTitle": "Parameters and request surface",
    "contract.required": "Required",
    "contract.responsesDetail":
      "Review response bodies grouped by status code, with field-level metadata preserved from the editor.",
    "contract.responsesEmpty": "No response fields were documented for this endpoint.",
    "contract.responsesEyebrow": "Response contract",
    "contract.responsesTitle": "Response envelopes and fields",
    "contract.unnamedField": "Unnamed field",
    "endpointStatus.archived": "Archived",
    "endpointStatus.deprecated": "Deprecated",
    "endpointStatus.draft": "Draft lane",
    "endpointStatus.released": "Released",
    "endpointStatus.review": "In review",
    "docs.authenticatedData": "All documentation is loaded from authenticated project APIs",
    "docs.badge.browseMode": "Browse mode",
    "docs.badge.readOnly": "Read-only",
    "docs.empty.noEndpoints": "This project does not contain any documented endpoints yet.",
    "docs.empty.select": "Choose an endpoint from the tree to inspect its read-only contract surface.",
    "docs.empty.title": "No endpoint selected",
    "docs.emptySearch": "No endpoints match the current documentation search.",
    "docs.filteredEndpoints": "Filtered to {count} endpoints",
    "docs.hero.noDescription": "No endpoint description was written for this contract.",
    "docs.loadingEndpoint": "Loading endpoint details...",
    "docs.loadingShell": "Loading documentation surface...",
    "docs.metric.mockReleases": "Mock releases",
    "docs.metric.parameters": "Parameters",
    "docs.metric.responses": "Responses",
    "docs.metric.versions": "Versions",
    "docs.mock.activeLatest": "Active latest",
    "docs.mock.detail":
      "Inspect the latest mock publication and keep a short release trail for reviewers and testers.",
    "docs.mock.empty": "No mock releases have been published for this endpoint.",
    "docs.mock.eyebrow": "Mock releases",
    "docs.mock.latest": "Latest",
    "docs.mock.latestPublication": "Latest publication",
    "docs.mock.publishedRelease": "Published release #{count}",
    "docs.mock.release": "Release #{count}",
    "docs.mock.timestampUnavailable": "Timestamp unavailable",
    "docs.mock.title": "Published mock runtime snapshots",
    "docs.module": "Module",
    "docs.navigation.detail": "Narrow the tree by endpoint name, method, path, module, or group label.",
    "docs.navigation.eyebrow": "Navigation",
    "docs.navigation.search": "Search docs",
    "docs.navigation.searchPlaceholder": "Search names, methods, paths, modules, groups",
    "docs.navigation.title": "Search and browse endpoints",
    "docs.openWorkbench": "Open workbench",
    "docs.page.description":
      "Browse endpoint contracts, release posture, and mock publication history without stepping into editing mode.",
    "docs.page.eyebrow": "Project documentation",
    "docs.stats.endpoints": "Endpoints",
    "docs.stats.groups": "Groups",
    "docs.stats.modules": "Modules",
    "docs.summary.endpoints": "{count} endpoints",
    "docs.summary.groupsAndEndpoints": "{groups} groups · {endpoints} endpoints",
    "docs.version.currentLane": "Current lane",
    "docs.version.detailDraft": "This endpoint is still in the draft lane and does not have a released version yet.",
    "docs.version.detailLive":
      "The documentation surface is highlighting the contract snapshot currently associated with runtime traffic.",
    "docs.version.draftLane": "Draft lane",
    "docs.version.livePrefix": "Live: {version}",
    "docs.version.liveSnapshot": "Live snapshot",
    "docs.version.noSummary": "No version summary was recorded.",
    "docs.version.noVersions": "No version snapshots were saved for this endpoint yet.",
    "docs.version.region": "Version posture",
    "docs.version.releasedBadge": "Released snapshot",
    "docs.version.snapshot": "Snapshot {version}",
    "docs.version.snapshotBadge": "Snapshot",
    "docs.version.title": "Live version",
    "docs.version.version": "Version {version}",
    "mockCenter.changedDrafts": "Changed drafts",
    "mockCenter.emptySearch": "No endpoints match the current search.",
    "mockCenter.heroEyebrow": "Mock runtime access",
    "mockCenter.heroSubtitle":
      "Control project-wide runtime posture, keep the shared token visible, and publish changed endpoints without hopping across editor tabs.",
    "mockCenter.heroTitle": "Mock center",
    "mockCenter.loading": "Loading mock center...",
    "mockCenter.mode.private.detail": "Only signed-in project readers can hit runtime mock traffic.",
    "mockCenter.mode.private.label": "Private mode",
    "mockCenter.mode.public.detail": "Anonymous callers can hit runtime mock traffic without auth.",
    "mockCenter.mode.public.label": "Public mode",
    "mockCenter.mode.token.detail": "Bearer auth or X-ApiHub-Mock-Token can pass runtime access.",
    "mockCenter.mode.token.label": "Token mode",
    "mockCenter.mockDisabled": "Mock disabled",
    "mockCenter.mockEnabledNotPublished": "Mock enabled but not published yet.",
    "mockCenter.publishAction": "Publish endpoint",
    "mockCenter.publishEyebrow": "Publish center",
    "mockCenter.publishSearch": "Search endpoints",
    "mockCenter.publishSearchPlaceholder": "Search endpoint names, methods, paths, or groups",
    "mockCenter.publishTitle": "Endpoint release posture",
    "mockCenter.published": "Published",
    "mockCenter.releaseLabel": "Release",
    "mockCenter.releaseValue": "Release #{count}",
    "mockCenter.responses": "Responses",
    "mockCenter.runtime.private": "Only signed-in users with project read access can call runtime mock traffic.",
    "mockCenter.runtime.public": "Public traffic is allowed for every caller.",
    "mockCenter.runtime.token":
      "Mock requests can use project auth or the shared X-ApiHub-Mock-Token header.",
    "mockCenter.runtimeCardTitle": "Mode cards and runtime token",
    "mockCenter.runtimeDrift": "Draft drift",
    "mockCenter.runtimeInSync": "In sync",
    "mockCenter.runtimeLatestPublished": "Latest runtime snapshot published {time}.",
    "mockCenter.runtimeToken": "Mock access token",
    "mockCenter.runtimeTokenEmpty": "No token set",
    "mockCenter.runtimeTokenPreview": "Token preview",
    "mockCenter.runtimeTitle":
      "Choose whether runtime traffic stays private, accepts a shared project token, or becomes fully public.",
    "mockCenter.runtimeBase": "Runtime base",
    "mockCenter.runtimeBaseDetail": "Project mock traffic can be replayed from this shared runtime entry.",
    "mockCenter.runtimeBaseHint": "Pair it with the shared token when token mode is enabled.",
    "mockCenter.rules": "Rules",
    "mockCenter.regenerateToken": "Regenerate token",
    "mockCenter.releaseNotPublished": "Not published",
    "mockCenter.saveAccess": "Save mock access",
    "mockCenter.searchUngrouped": "Ungrouped",
    "mockCenter.visibleEndpoints": "Visible endpoints",
    "parameterSection.body": "Body parameters",
    "parameterSection.cookie": "Cookie parameters",
    "parameterSection.header": "Header parameters",
    "parameterSection.path": "Path parameters",
    "parameterSection.query": "Query parameters",
    "project.access.admin": "Project admin access",
    "project.access.editor": "Editor access",
    "project.access.fallback": "Project access",
    "project.access.tester": "Tester access",
    "project.access.viewer": "Viewer access",
    "project.action.browseDocs": "Browse docs",
    "project.action.enter": "Enter workspace",
    "project.action.open": "Open",
    "project.badge.manage": "Can manage members",
    "project.badge.readOnly": "Read-only",
    "project.badge.review": "Member review",
    "project.badge.writable": "Writable",
    "project.debugRuleCount": "{count} debug rule",
    "project.debugRuleCount_plural": "{count} debug rules",
    "project.fallbackDescription":
      "Structured API docs, grouped endpoints, and version snapshots in one workspace.",
    "project.runtimePosture": "Runtime posture",
    "publicShare.badge.noExpiry": "No expiry",
    "publicShare.badge.validUntil": "Valid until {date}",
    "publicShare.contractEyebrow": "Contract surface",
    "publicShare.defaultDescription": "Shared read-only documentation surface.",
    "publicShare.empty.noEndpoints": "This share does not expose any documented endpoints yet.",
    "publicShare.empty.select": "Adjust the search or choose a visible endpoint from the shared tree.",
    "publicShare.empty.title": "No endpoint selected",
    "publicShare.emptySearch": "No endpoints match the current documentation search.",
    "publicShare.loadingEndpoint": "Loading shared endpoint...",
    "publicShare.loadingShell": "Loading public documentation...",
    "publicShare.mockEyebrow": "Mock releases",
    "publicShare.mockTitle": "Published runtime snapshots",
    "publicShare.navigation.detail":
      "Filter the shared tree by endpoint name, method, path, module, or group label.",
    "publicShare.navigation.eyebrow": "Navigation",
    "publicShare.navigation.search": "Search docs",
    "publicShare.navigation.searchPlaceholder": "Search endpoints, modules, groups, paths",
    "publicShare.navigation.title": "Search and browse endpoints",
    "publicShare.pageEyebrow": "Public documentation share",
    "publicShare.shareDefault": "Shared docs",
    "publicShare.stats.endpoints": "Endpoints",
    "publicShare.stats.groups": "Groups",
    "publicShare.stats.modules": "Modules",
    "publicShare.summary.endpoints": "{count} endpoints",
    "publicShare.version.currentLane": "Current lane",
    "publicShare.version.draftLane": "Draft lane",
    "publicShare.version.liveSnapshot": "Live snapshot",
    "publicShare.version.region": "Version posture",
    "publicShare.version.title": "Live version",
    "session.backToProjects": "Back to projects",
    "session.changeToChinese": "Switch to Chinese",
    "session.changeToEnglish": "Switch to English",
    "session.loading": "Loading session...",
    "session.signOut": "Sign out",
    "session.signingOut": "Signing out...",
    "session.preferenceLabel": "Preferences",
    "session.localeSwitch.en": "EN",
    "session.localeSwitch.zh": "中文",
    "session.themeSwitch.dark": "Dark",
    "session.themeSwitch.light": "Light",
    "session.themeSwitch.system": "Auto",
    "session.themeDark": "Switch to dark mode",
    "session.themeLight": "Switch to light mode",
    "session.themeSystem": "Follow system theme",
    "session.title": "Session",
    "shareDesk.activeCount": "{count} active",
    "shareDesk.createAction": "Create share link",
    "shareDesk.createDescription":
      "Name the audience, set optional expiry, and publish a share code that can be disabled instantly.",
    "shareDesk.createEyebrow": "Create link",
    "shareDesk.createTitle": "Release a curated public URL",
    "shareDesk.descriptionLabel": "Share description",
    "shareDesk.disable": "Disable link",
    "shareDesk.empty": "No share links were created for this project yet.",
    "shareDesk.emptyDescription": "No description provided for this share link.",
    "shareDesk.enable": "Enable link",
    "shareDesk.expiredCount": "{count} expired",
    "shareDesk.expiryLabel": "Share expiry",
    "shareDesk.expiryLabelById": "Expiry {id}",
    "shareDesk.heroEyebrow": "Publication desk",
    "shareDesk.heroSubtitle":
      "Create revocable public documentation links, tune expiry, and hand reviewers a cleaner browse surface than the full authenticated workbench.",
    "shareDesk.heroTitle": "Share docs",
    "shareDesk.loading": "Loading share links...",
    "shareDesk.placeholder.description": "Read-only contract access for partners, QA, or launch review.",
    "shareDesk.placeholder.name": "External reviewers",
    "shareDesk.liveEyebrow": "Live links",
    "shareDesk.liveTitle": "Managed share inventory",
    "shareDesk.nameLabel": "Share name",
    "shareDesk.nameLabelById": "Share name {id}",
    "shareDesk.noExpiry": "No expiry",
    "shareDesk.openPublicPage": "Open public page",
    "shareDesk.projectLabel": "Project #{id}",
    "shareDesk.publicUrl": "Public URL",
    "shareDesk.saveDetails": "Save details",
    "shareDesk.saveExpiry": "Save expiry",
    "shareDesk.state.disabled": "Disabled",
    "shareDesk.state.enabled": "Enabled",
    "shareDesk.state.expired": "Expired",
    "shareDesk.totalCount": "{count} total links",
    "shareDesk.validUntil": "Expires {date}",
    "shareDesk.validUntilShort": "Expires {date}",
    "shareDesk.copy": "Copy link",
    "shareDesk.copied": "Copied",
    "shareDesk.descriptionLabelById": "Share description {id}",
    "members.eyebrow": "Members",
    "members.title": "Collaborators",
    "members.detail":
      "Review who can shape the API workspace, keep the owner seat protected, and make role changes without leaving the console.",
    "members.metric.members": "Members",
    "members.metric.admins": "Admins",
    "members.banner.manage":
      "Project admins can add collaborators, rebalance roles, and keep at least one admin seat protected.",
    "members.banner.readOnly": "You can review project access, but only project admins can change membership.",
    "members.form.username": "Project member username",
    "members.form.role": "Project member role",
    "members.form.add": "Add project member",
    "members.empty": "No project members yet.",
    "members.card.owner": "Owner",
    "members.card.protectedSeat": "Protected seat",
    "members.card.roleAssignment": "Role assignment",
    "members.card.projectOwner": "Project owner",
    "members.card.roleLabel": "Member {id} role",
    "members.card.save": "Save member",
    "members.card.saveLabel": "Save member {id}",
    "members.card.delete": "Delete member",
    "members.card.deleteLabel": "Delete member {id}",
    "members.card.keepAdmin": "Keep at least one project admin assigned before changing this role.",
    "members.card.readOnly": "Read-only for your role",
    "members.role.project_admin": "Project admin",
    "members.role.editor": "Editor",
    "members.role.tester": "Tester",
    "members.role.viewer": "Viewer",
    "debug.eyebrow": "Debug",
    "debug.title": "Live request console",
    "debug.detail": "Run the selected endpoint against the active environment without leaving the workbench.",
    "debug.empty": "Select both an endpoint and an environment to enable debugging.",
    "debug.executeError": "Failed to execute debug request",
    "debug.targetEnvironment": "Target environment",
    "debug.endpointRoute": "Endpoint route",
    "debug.queryString": "Query string",
    "debug.headers": "Headers",
    "debug.body": "Body",
    "debug.preview": "Request preview",
    "debug.previewInvalid": "Invalid target",
    "debug.send": "Send request",
    "debug.sending": "Sending...",
    "debug.responseHeaders": "Response headers",
    "debug.responseHeadersEmpty": "No response headers.",
    "debug.responseBody": "Response body",
    "debug.responseBodyEmpty": "<empty>",
    "debug.presets.eyebrow": "Request presets",
    "debug.presets.title": "Keep your best debug drafts one click away.",
    "debug.presets.detail": "Saved locally in this browser and scoped to the current endpoint.",
    "debug.presets.name": "Preset name",
    "debug.presets.placeholder": "Strict user trace",
    "debug.presets.save": "Save preset",
    "debug.presets.saveError": "Failed to save preset.",
    "debug.presets.empty": "No presets yet. Save a draft you want to reuse across repeated debugging runs.",
    "debug.presets.savedBadge": "Saved",
    "debug.presets.apply": "Apply",
    "debug.presets.applyLabel": "Apply preset {name}",
    "debug.presets.delete": "Delete",
    "debug.presets.deleteLabel": "Delete preset {name}",
    "debug.presets.savedMessage": "Saved preset {name}.",
    "debug.presets.appliedMessage": "Applied preset {name}.",
    "debug.presets.deletedMessage": "Deleted preset {name}.",
    "debug.curl.eyebrow": "cURL bridge",
    "debug.curl.title": "Move the current draft in and out of terminal flows.",
    "debug.curl.detail": "Export the exact request you are about to run, or paste a cURL command back into this console.",
    "debug.curl.generated": "Generated cURL",
    "debug.curl.copy": "Copy cURL",
    "debug.curl.import": "Import cURL",
    "debug.curl.importPlaceholder": "curl 'https://local.dev/users/{id}?mode=compact' -H 'X-Trace: imported'",
    "debug.curl.importAction": "Import cURL",
    "debug.curl.empty": "No cURL command is available yet.",
    "debug.curl.clipboardUnavailable": "Clipboard is unavailable in this browser.",
    "debug.curl.copied": "Copied cURL command.",
    "debug.curl.copyError": "Failed to copy cURL command.",
    "debug.curl.imported": "Imported cURL into the current draft.",
    "debug.curl.methodMismatch": "Imported method {imported} differs from endpoint {endpoint}.",
    "debug.curl.importError": "Failed to import cURL command.",
    "debug.policy.title": "Debug target policy",
    "debug.policy.projectRules": "Project rules",
    "debug.policy.environmentMode": "Environment mode",
    "debug.policy.environmentRules": "Environment rules",
    "debug.policy.blockedTitle": "Request blocked by debug policy",
    "debug.policy.blockedHost": "Blocked host",
    "debug.policy.matchedRules": "Matched rules",
    "debug.policy.summary.append": "Effective policy uses global + project rules, then appends environment rules.",
    "debug.policy.summary.override": "Effective policy uses global rules plus environment rules, overriding project rules.",
    "debug.policy.summary.inherit": "Effective policy uses global + project rules.",
    "debug.history.eyebrow": "Recent history",
    "debug.history.environmentFilter": "Debug history environment filter",
    "debug.history.statusFilter": "Debug history status filter",
    "debug.history.createdFrom": "Debug history created from filter",
    "debug.history.createdTo": "Debug history created to filter",
    "debug.history.allEnvironments": "All environments",
    "debug.history.statusCode": "Status code",
    "debug.history.clear": "Clear debug history",
    "debug.history.loading": "Loading history...",
    "debug.history.empty": "No debug history yet.",
    "debug.history.replay": "Replay",
    "debug.history.replayLabel": "Replay history {id}",
    "debug.history.run": "Run again",
    "debug.history.runLabel": "Run history {id}",
    "sidebar.moduleSummary": "{groups} groups · {endpoints} endpoints",
    "tree.endpointCount": "{count} endpoints",
    "tree.groupsAndEndpoints": "{groups} groups / {endpoints} endpoints",
    "tree.moduleBadge": "Module",
    "tree.routeSummary": "{method} {path}",
    "workbench.tab.debug": "Debug",
    "workbench.tab.documentation": "Documentation",
    "workbench.tab.environments": "Environments",
    "workbench.heroEyebrow": "Project workbench",
    "workbench.heroSubtitle":
      "Compact lanes for documentation, runtime debugging, environments, and collaborator control.",
    "workbench.badge.writable": "Writable",
    "workbench.badge.readOnly": "Read-only",
    "workbench.action.browseDocs": "Browse docs",
    "workbench.action.shareDocs": "Share docs",
    "workbench.action.mockCenter": "Mock center",
    "workbench.stats.modules": "Modules",
    "workbench.stats.groups": "Groups",
    "workbench.stats.endpoints": "Endpoints",
    "workbench.lanesTitle": "Workbench lanes",
    "workbench.searchTree": "Search tree",
    "workbench.searchTreePlaceholder": "Search modules, groups, endpoints, or paths",
    "workbench.tab.members": "Members",
    "workbench.tab.mock": "Mock",
    "workbench.tab.overview": "Overview",
    "workbench.overview.eyebrow": "Workspace focus",
    "workbench.overview.title": "Project rhythm at a glance",
    "workbench.overview.detail":
      "Use documentation for contract editing, mock for runtime shaping, debug for live requests, and members for project governance.",
    "workbench.overview.card.documentation.eyebrow": "Documentation lane",
    "workbench.overview.card.documentation.title": "{moduleCount} modules · {groupCount} groups",
    "workbench.overview.card.documentation.detail":
      "Keep endpoint structure compact and searchable instead of scrolling through every panel at once.",
    "workbench.overview.card.runtime.eyebrow": "Runtime lane",
    "workbench.overview.card.runtime.title": "{environmentCount} environments · {debugCount} debug records",
    "workbench.overview.card.runtime.detail": "Separate runtime validation from contract editing so each lane stays focused.",
    "workbench.overview.card.members.eyebrow": "Members lane",
    "workbench.overview.card.members.title": "{memberCount} collaborators · {adminCount} admin seats",
    "workbench.overview.card.members.detail":
      "Open the members lane when you need to rebalance roles or review ownership.",
    "workbench.overview.card.mock.eyebrow": "Mock lane",
    "workbench.overview.card.mock.title": "{mockCount} published mock releases",
    "workbench.overview.card.mock.detail":
      "Pin mock work into its own lane so draft rules and published runtime stay easy to compare.",
    "workbench.overview.activeEndpoint.eyebrow": "Active endpoint",
    "workbench.overview.activeEndpoint.emptyTitle": "No endpoint selected",
    "workbench.overview.activeEndpoint.emptyDetail": "Open the documentation lane to select an endpoint.",
    "workbench.documentation.loadingTree": "Loading project tree...",
    "workbench.documentation.emptySearch": "No matching nodes."
  },
  "zh-CN": {
    "catalog.createProject": "创建项目",
    "catalog.consoleBadge": "分组优先",
    "catalog.empty": "没有匹配的项目，请调整搜索词或切换项目分组。",
    "catalog.emptyAll": "还没有项目工作区",
    "catalog.emptyAllDetail": "创建第一个项目后，你就可以开始组织接口、调试策略和 Mock 运行时快照。",
    "catalog.group.all": "全部项目",
    "catalog.group.all.description": "查看你在当前控制台可访问的全部项目。",
    "catalog.group.editable": "可编辑",
    "catalog.group.editable.description": "你可以直接维护 API 和运行时行为的项目。",
    "catalog.group.manage": "成员管理",
    "catalog.group.manage.description": "你可以调整协作者和权限席位的项目。",
    "catalog.group.review": "只读审阅",
    "catalog.group.review.description": "用于查阅、验收和只读评审的项目。",
    "catalog.heading": "项目指挥台",
    "catalog.heroDetail": "先从项目分组进入，再落到你真正要编辑、审阅或治理的工作区。",
    "catalog.activeGroup": "当前分组",
    "catalog.visibleProjects": "可见项目",
    "catalog.filteredBy": "已按“{query}”筛选",
    "catalog.ready": "可以继续进入下一个工作区。",
    "catalog.loading": "正在加载项目...",
    "catalog.search": "搜索项目",
    "catalog.searchPlaceholder": "按项目名称、标识或描述搜索",
    "catalog.subtitle": "先选择分组，再进入对应的 API 项目工作区。",
    "catalog.title": "项目",
    "catalog.inventoryEyebrow": "项目库",
    "catalog.inventoryTitle": "{group} 下的项目",
    "catalog.inventoryDetail": "当前有 {count} 个工作区可以继续进入。",
    "catalog.radarEyebrow": "优先通道",
    "catalog.radarTitle": "项目雷达",
    "catalog.radarDetail": "保持“先分组，后项目”的路径，再直接跳转到当前最值得优先处理的工作区。",
    "catalog.radarScope": "范围：{group}",
    "catalog.radarVisibleCount": "当前可见 {count} 个项目",
    "catalog.radarEmpty": "这个通道暂时还没有可见项目。",
    "catalog.radar.manage": "治理",
    "catalog.radar.writable": "可编辑",
    "catalog.radar.review": "评审",
    "catalog.pulseEyebrow": "运营脉搏",
    "catalog.pulseTitle": "运营脉搏",
    "catalog.pulseDetail": "在进入具体工作区之前，先快速看清分组覆盖、权限压力和运行时安全状态。",
    "catalog.pulse.groups": "项目分组",
    "catalog.pulse.writable": "可编辑通道",
    "catalog.pulse.governance": "治理席位",
    "catalog.pulse.debugRules": "调试规则",
    "catalog.pulse.coverageLabel": "可编辑覆盖率",
    "catalog.pulse.coverageDetail": "当前项目库中有 {editable} / {total} 个项目可以直接编辑。",
    "catalog.createDrawer.closeOverlay": "关闭创建项目遮罩",
    "catalog.createDrawer.closePanel": "关闭项目创建面板",
    "catalog.createDrawer.eyebrow": "新工作区",
    "catalog.createDrawer.title": "创建项目",
    "catalog.createDrawer.detail": "从一个干净的项目 key、第一个管理席位和空的调试策略基线开始搭建新的 API 工作区。",
    "catalog.createDrawer.close": "关闭",
    "catalog.createDrawer.preview": "即时预览",
    "catalog.createDrawer.projectKeyFallback": "project-key",
    "catalog.createDrawer.projectName": "项目名称",
    "catalog.createDrawer.projectKey": "项目 key",
    "catalog.createDrawer.projectDescription": "项目描述",
    "catalog.createDrawer.namePlaceholder": "结算中心",
    "catalog.createDrawer.keyPlaceholder": "billing-hub",
    "catalog.createDrawer.descriptionPlaceholder": "结算 API、对账流程和出款 webhook 都可以放在这个工作区里。",
    "catalog.createDrawer.submit": "创建工作区",
    "catalog.createDrawer.submitting": "正在创建...",
    "catalog.createDrawer.error.nameRequired": "请填写项目名称。",
    "catalog.createDrawer.error.keyRequired": "请填写项目 key。",
    "catalog.createDrawer.error.keyFormat": "只能使用小写字母、数字和连字符。",
    "catalog.createDrawer.error.descriptionTooLong": "描述请控制在 280 个字符以内。",
    "contract.example": "示例：{value}",
    "contract.fields": "{count} 个字段",
    "contract.fields_plural": "{count} 个字段",
    "contract.noDescription": "暂无字段说明。",
    "contract.optional": "可选",
    "contract.parametersDetail": "按传输位置查看请求结构，让接入方能快速扫清契约边界。",
    "contract.parametersEmpty": "当前接口还没有记录请求参数。",
    "contract.parametersEyebrow": "请求契约",
    "contract.parametersTitle": "参数与请求面",
    "contract.required": "必填",
    "contract.responsesDetail": "按状态码查看响应结构，并保留编辑器中的字段级元信息。",
    "contract.responsesEmpty": "当前接口还没有记录响应字段。",
    "contract.responsesEyebrow": "响应契约",
    "contract.responsesTitle": "响应包络与字段",
    "contract.unnamedField": "未命名字段",
    "endpointStatus.archived": "已归档",
    "endpointStatus.deprecated": "已废弃",
    "endpointStatus.draft": "草稿泳道",
    "endpointStatus.released": "已发布",
    "endpointStatus.review": "审核中",
    "docs.authenticatedData": "全部文档均来自已认证的项目接口",
    "docs.badge.browseMode": "浏览模式",
    "docs.badge.readOnly": "只读",
    "docs.empty.noEndpoints": "这个项目暂时还没有已编目的接口。",
    "docs.empty.select": "从左侧树中选择一个接口，查看它的只读契约面。",
    "docs.empty.title": "未选择接口",
    "docs.emptySearch": "当前文档搜索没有匹配的接口。",
    "docs.filteredEndpoints": "已筛选到 {count} 个接口",
    "docs.hero.noDescription": "这个契约还没有填写接口说明。",
    "docs.loadingEndpoint": "正在加载接口详情...",
    "docs.loadingShell": "正在加载文档界面...",
    "docs.metric.mockReleases": "Mock 发布",
    "docs.metric.parameters": "参数",
    "docs.metric.responses": "响应",
    "docs.metric.versions": "版本",
    "docs.mock.activeLatest": "当前最新",
    "docs.mock.detail": "查看最新 Mock 发布，并为评审和测试保留清晰的发布轨迹。",
    "docs.mock.empty": "这个接口还没有发布任何 Mock 快照。",
    "docs.mock.eyebrow": "Mock 发布",
    "docs.mock.latest": "最新",
    "docs.mock.latestPublication": "最近发布",
    "docs.mock.publishedRelease": "发布 #{count}",
    "docs.mock.release": "发布 #{count}",
    "docs.mock.timestampUnavailable": "暂无时间戳",
    "docs.mock.title": "已发布的 Mock 运行时快照",
    "docs.module": "模块",
    "docs.navigation.detail": "按接口名、方法、路径、模块或分组标签缩小树形范围。",
    "docs.navigation.eyebrow": "导航",
    "docs.navigation.search": "搜索文档",
    "docs.navigation.searchPlaceholder": "搜索名称、方法、路径、模块或分组",
    "docs.navigation.title": "搜索并浏览接口",
    "docs.openWorkbench": "打开工作台",
    "docs.page.description": "在不进入编辑模式的情况下，浏览接口契约、发布态势和 Mock 历史。",
    "docs.page.eyebrow": "项目文档",
    "docs.stats.endpoints": "接口",
    "docs.stats.groups": "分组",
    "docs.stats.modules": "模块",
    "docs.summary.endpoints": "{count} 个接口",
    "docs.summary.groupsAndEndpoints": "{groups} 个分组 · {endpoints} 个接口",
    "docs.version.currentLane": "当前泳道",
    "docs.version.detailDraft": "当前接口仍处于草稿泳道，还没有正式发布版本。",
    "docs.version.detailLive": "文档界面正在高亮当前与运行时流量关联的契约快照。",
    "docs.version.draftLane": "草稿泳道",
    "docs.version.livePrefix": "线上：{version}",
    "docs.version.liveSnapshot": "线上快照",
    "docs.version.noSummary": "暂无版本说明。",
    "docs.version.noVersions": "这个接口还没有保存任何版本快照。",
    "docs.version.region": "版本态势",
    "docs.version.releasedBadge": "已发布快照",
    "docs.version.snapshot": "快照 {version}",
    "docs.version.snapshotBadge": "快照",
    "docs.version.title": "线上版本",
    "docs.version.version": "版本 {version}",
    "mockCenter.changedDrafts": "变更草稿",
    "mockCenter.emptySearch": "当前搜索没有匹配的接口。",
    "mockCenter.heroEyebrow": "Mock 运行时访问",
    "mockCenter.heroSubtitle": "统一控制项目级运行时姿态、保留共享令牌，并在不切换编辑标签的情况下发布已变更接口。",
    "mockCenter.heroTitle": "Mock 中心",
    "mockCenter.loading": "正在加载 Mock 中心...",
    "mockCenter.mode.private.detail": "只有已登录且具备项目读权限的用户可以访问运行时 Mock 流量。",
    "mockCenter.mode.private.label": "私有模式",
    "mockCenter.mode.public.detail": "匿名调用方也可以直接访问运行时 Mock 流量。",
    "mockCenter.mode.public.label": "公开模式",
    "mockCenter.mode.token.detail": "可通过 Bearer 鉴权或 X-ApiHub-Mock-Token 访问运行时。",
    "mockCenter.mode.token.label": "令牌模式",
    "mockCenter.mockDisabled": "Mock 未启用",
    "mockCenter.mockEnabledNotPublished": "Mock 已启用，但尚未发布。",
    "mockCenter.publishAction": "发布接口",
    "mockCenter.publishEyebrow": "发布中心",
    "mockCenter.publishSearch": "搜索接口",
    "mockCenter.publishSearchPlaceholder": "搜索接口名称、方法、路径或分组",
    "mockCenter.publishTitle": "接口发布态势",
    "mockCenter.published": "已发布",
    "mockCenter.releaseLabel": "发布",
    "mockCenter.releaseValue": "发布 #{count}",
    "mockCenter.responses": "响应",
    "mockCenter.runtime.private": "只有已登录且具备项目读权限的用户可以访问运行时 Mock 流量。",
    "mockCenter.runtime.public": "所有调用方都可以访问公开 Mock 流量。",
    "mockCenter.runtime.token": "Mock 请求可以使用项目鉴权，或携带共享的 X-ApiHub-Mock-Token 头。",
    "mockCenter.runtimeCardTitle": "模式卡片与运行时令牌",
    "mockCenter.runtimeDrift": "草稿有漂移",
    "mockCenter.runtimeInSync": "与发布一致",
    "mockCenter.runtimeLatestPublished": "最近一次运行时快照发布于 {time}。",
    "mockCenter.runtimeToken": "Mock 访问令牌",
    "mockCenter.runtimeTokenEmpty": "未设置令牌",
    "mockCenter.runtimeTokenPreview": "令牌预览",
    "mockCenter.runtimeTitle": "选择运行时流量保持私有、接受共享令牌，还是完全公开。",
    "mockCenter.runtimeBase": "运行时入口",
    "mockCenter.runtimeBaseDetail": "项目级 Mock 流量会统一从这个共享运行时入口进入。",
    "mockCenter.runtimeBaseHint": "启用令牌模式后，可配合共享令牌一起分发给调用方。",
    "mockCenter.rules": "规则",
    "mockCenter.regenerateToken": "重新生成令牌",
    "mockCenter.releaseNotPublished": "未发布",
    "mockCenter.saveAccess": "保存 Mock 访问",
    "mockCenter.searchUngrouped": "未分组",
    "mockCenter.visibleEndpoints": "可见接口",
    "parameterSection.body": "Body 参数",
    "parameterSection.cookie": "Cookie 参数",
    "parameterSection.header": "Header 参数",
    "parameterSection.path": "路径参数",
    "parameterSection.query": "查询参数",
    "project.access.admin": "项目管理员权限",
    "project.access.editor": "编辑权限",
    "project.access.fallback": "项目权限",
    "project.access.tester": "测试权限",
    "project.access.viewer": "查看权限",
    "project.action.browseDocs": "浏览文档",
    "project.action.enter": "进入工作台",
    "project.action.open": "打开",
    "project.badge.manage": "可管理成员",
    "project.badge.readOnly": "只读",
    "project.badge.review": "成员审阅",
    "project.badge.writable": "可编辑",
    "project.debugRuleCount": "{count} 条调试规则",
    "project.debugRuleCount_plural": "{count} 条调试规则",
    "project.fallbackDescription": "在一个工作区里统一管理 API 文档、分组接口和版本快照。",
    "project.runtimePosture": "运行时态势",
    "publicShare.badge.noExpiry": "无有效期",
    "publicShare.badge.validUntil": "有效期至 {date}",
    "publicShare.contractEyebrow": "契约视图",
    "publicShare.defaultDescription": "共享的只读文档界面。",
    "publicShare.empty.noEndpoints": "这个分享暂时还没有暴露任何已编目的接口。",
    "publicShare.empty.select": "请调整搜索条件，或从共享树中选择一个可见接口。",
    "publicShare.empty.title": "未选择接口",
    "publicShare.emptySearch": "当前文档搜索没有匹配的接口。",
    "publicShare.loadingEndpoint": "正在加载共享接口...",
    "publicShare.loadingShell": "正在加载公开文档...",
    "publicShare.mockEyebrow": "Mock 发布",
    "publicShare.mockTitle": "已发布的运行时快照",
    "publicShare.navigation.detail": "按接口名、方法、路径、模块或分组标签过滤共享树。",
    "publicShare.navigation.eyebrow": "导航",
    "publicShare.navigation.search": "搜索文档",
    "publicShare.navigation.searchPlaceholder": "搜索接口、模块、分组或路径",
    "publicShare.navigation.title": "搜索并浏览接口",
    "publicShare.pageEyebrow": "公开文档分享",
    "publicShare.shareDefault": "共享文档",
    "publicShare.stats.endpoints": "接口",
    "publicShare.stats.groups": "分组",
    "publicShare.stats.modules": "模块",
    "publicShare.summary.endpoints": "{count} 个接口",
    "publicShare.version.currentLane": "当前泳道",
    "publicShare.version.draftLane": "草稿泳道",
    "publicShare.version.liveSnapshot": "线上快照",
    "publicShare.version.region": "版本态势",
    "publicShare.version.title": "线上版本",
    "session.backToProjects": "返回项目列表",
    "session.changeToChinese": "切换为中文",
    "session.changeToEnglish": "切换为英文",
    "session.loading": "正在加载会话...",
    "session.signOut": "退出登录",
    "session.signingOut": "正在退出...",
    "session.preferenceLabel": "偏好",
    "session.localeSwitch.en": "EN",
    "session.localeSwitch.zh": "中文",
    "session.themeSwitch.dark": "深色",
    "session.themeSwitch.light": "浅色",
    "session.themeSwitch.system": "跟随",
    "session.themeDark": "切换为深色模式",
    "session.themeLight": "切换为浅色模式",
    "session.themeSystem": "跟随系统主题",
    "session.title": "会话",
    "shareDesk.activeCount": "{count} 个启用中",
    "shareDesk.createAction": "创建分享链接",
    "shareDesk.createDescription": "为受众命名、设置可选有效期，并发布可随时关闭的分享码。",
    "shareDesk.createEyebrow": "创建链接",
    "shareDesk.createTitle": "发布一个精选公开地址",
    "shareDesk.descriptionLabel": "分享描述",
    "shareDesk.descriptionLabelById": "分享描述 {id}",
    "shareDesk.disable": "禁用链接",
    "shareDesk.empty": "这个项目还没有创建任何分享链接。",
    "shareDesk.emptyDescription": "这个分享链接还没有填写描述。",
    "shareDesk.enable": "启用链接",
    "shareDesk.expiredCount": "{count} 个已过期",
    "shareDesk.expiryLabel": "分享有效期",
    "shareDesk.expiryLabelById": "有效期 {id}",
    "shareDesk.heroEyebrow": "发布台",
    "shareDesk.heroSubtitle": "创建可撤销的公开文档链接，控制有效期，并给评审者一个比完整工作台更干净的浏览界面。",
    "shareDesk.heroTitle": "分享文档",
    "shareDesk.loading": "正在加载分享链接...",
    "shareDesk.placeholder.description": "提供给合作方、QA 或上线评审的只读合同访问说明。",
    "shareDesk.placeholder.name": "外部评审成员",
    "shareDesk.liveEyebrow": "在线链接",
    "shareDesk.liveTitle": "受管的分享清单",
    "shareDesk.nameLabel": "分享名称",
    "shareDesk.nameLabelById": "分享名称 {id}",
    "shareDesk.noExpiry": "无有效期",
    "shareDesk.openPublicPage": "打开公开页面",
    "shareDesk.projectLabel": "项目 #{id}",
    "shareDesk.publicUrl": "公开地址",
    "shareDesk.saveDetails": "保存详情",
    "shareDesk.saveExpiry": "保存有效期",
    "shareDesk.state.disabled": "已禁用",
    "shareDesk.state.enabled": "启用中",
    "shareDesk.state.expired": "已过期",
    "shareDesk.totalCount": "{count} 个链接总数",
    "shareDesk.validUntil": "有效期 {date}",
    "shareDesk.validUntilShort": "有效期 {date}",
    "shareDesk.copy": "复制链接",
    "shareDesk.copied": "已复制",
    "members.eyebrow": "成员",
    "members.title": "协作者",
    "members.detail": "查看谁可以塑造 API 工作区，保护所有者席位，并在不离开控制台的情况下完成角色调整。",
    "members.metric.members": "成员",
    "members.metric.admins": "管理员",
    "members.banner.manage": "项目管理员可以添加协作者、重新平衡角色分配，并确保至少保留一个管理员席位。",
    "members.banner.readOnly": "你可以查看项目访问权限，但只有项目管理员可以修改成员关系。",
    "members.form.username": "项目成员用户名",
    "members.form.role": "项目成员角色",
    "members.form.add": "添加项目成员",
    "members.empty": "当前还没有项目成员。",
    "members.card.owner": "所有者",
    "members.card.protectedSeat": "受保护席位",
    "members.card.roleAssignment": "角色分配",
    "members.card.projectOwner": "项目所有者",
    "members.card.roleLabel": "成员 {id} 角色",
    "members.card.save": "保存成员",
    "members.card.saveLabel": "保存成员 {id}",
    "members.card.delete": "删除成员",
    "members.card.deleteLabel": "删除成员 {id}",
    "members.card.keepAdmin": "在修改此角色前，请先确保至少保留一个项目管理员。",
    "members.card.readOnly": "当前角色只读",
    "members.role.project_admin": "项目管理员",
    "members.role.editor": "编辑者",
    "members.role.tester": "测试者",
    "members.role.viewer": "查看者",
    "debug.eyebrow": "调试",
    "debug.title": "实时请求控制台",
    "debug.detail": "在不离开工作台的情况下，用当前环境直接运行选中的接口。",
    "debug.empty": "请同时选择一个接口和一个环境后再开始调试。",
    "debug.executeError": "调试请求执行失败",
    "debug.targetEnvironment": "目标环境",
    "debug.endpointRoute": "接口路由",
    "debug.queryString": "查询串",
    "debug.headers": "请求头",
    "debug.body": "请求体",
    "debug.preview": "请求预览",
    "debug.previewInvalid": "目标地址无效",
    "debug.send": "发送请求",
    "debug.sending": "发送中...",
    "debug.responseHeaders": "响应头",
    "debug.responseHeadersEmpty": "当前没有响应头。",
    "debug.responseBody": "响应体",
    "debug.responseBodyEmpty": "<空>",
    "debug.presets.eyebrow": "请求预设",
    "debug.presets.title": "把最好用的调试草稿保留在一键可达的位置。",
    "debug.presets.detail": "仅保存在当前浏览器，并且只作用于当前接口。",
    "debug.presets.name": "预设名称",
    "debug.presets.placeholder": "严格用户链路",
    "debug.presets.save": "保存预设",
    "debug.presets.saveError": "保存预设失败。",
    "debug.presets.empty": "还没有预设。把你想反复复用的调试草稿先保存下来。",
    "debug.presets.savedBadge": "已保存",
    "debug.presets.apply": "应用",
    "debug.presets.applyLabel": "应用预设 {name}",
    "debug.presets.delete": "删除",
    "debug.presets.deleteLabel": "删除预设 {name}",
    "debug.presets.savedMessage": "已保存预设 {name}。",
    "debug.presets.appliedMessage": "已应用预设 {name}。",
    "debug.presets.deletedMessage": "已删除预设 {name}。",
    "debug.curl.eyebrow": "cURL 桥接",
    "debug.curl.title": "让当前草稿在控制台流程与工作台之间来回切换。",
    "debug.curl.detail": "导出即将执行的准确请求，或把一条 cURL 命令直接贴回这个控制台。",
    "debug.curl.generated": "生成的 cURL",
    "debug.curl.copy": "复制 cURL",
    "debug.curl.import": "导入 cURL",
    "debug.curl.importPlaceholder": "curl 'https://local.dev/users/{id}?mode=compact' -H 'X-Trace: imported'",
    "debug.curl.importAction": "导入 cURL",
    "debug.curl.empty": "当前还没有可用的 cURL 命令。",
    "debug.curl.clipboardUnavailable": "当前浏览器不支持剪贴板。",
    "debug.curl.copied": "已复制 cURL 命令。",
    "debug.curl.copyError": "复制 cURL 命令失败。",
    "debug.curl.imported": "已把 cURL 导入当前草稿。",
    "debug.curl.methodMismatch": "导入的方法 {imported} 与当前接口方法 {endpoint} 不一致。",
    "debug.curl.importError": "导入 cURL 命令失败。",
    "debug.policy.title": "调试目标策略",
    "debug.policy.projectRules": "项目规则",
    "debug.policy.environmentMode": "环境模式",
    "debug.policy.environmentRules": "环境规则",
    "debug.policy.blockedTitle": "请求被调试策略拦截",
    "debug.policy.blockedHost": "被拦截的主机",
    "debug.policy.matchedRules": "命中的规则",
    "debug.policy.summary.append": "最终策略会先使用全局规则和项目规则，再追加环境规则。",
    "debug.policy.summary.override": "最终策略会使用全局规则和环境规则，并覆盖项目规则。",
    "debug.policy.summary.inherit": "最终策略会使用全局规则和项目规则。",
    "debug.history.eyebrow": "最近历史",
    "debug.history.environmentFilter": "调试历史环境筛选",
    "debug.history.statusFilter": "调试历史状态码筛选",
    "debug.history.createdFrom": "调试历史开始时间筛选",
    "debug.history.createdTo": "调试历史结束时间筛选",
    "debug.history.allEnvironments": "全部环境",
    "debug.history.statusCode": "状态码",
    "debug.history.clear": "清空调试历史",
    "debug.history.loading": "正在加载历史记录...",
    "debug.history.empty": "还没有调试历史。",
    "debug.history.replay": "回放",
    "debug.history.replayLabel": "回放历史 {id}",
    "debug.history.run": "再次运行",
    "debug.history.runLabel": "再次运行历史 {id}",
    "Project Tree": "项目树",
    "Modules and endpoints": "模块与接口",
    "New module name": "新模块名称",
    "Core": "核心",
    "Add module": "添加模块",
    "No matching nodes.": "没有匹配的节点。",
    "Quick access": "快捷访问",
    "Pinned routes and recent focus lanes.": "固定路由与最近聚焦泳道",
    "Personal shortcuts stay local to this browser and help you jump past large project trees.": "这些个人快捷入口只保存在当前浏览器里，帮你跨过庞大的项目树快速落位。",
    "Pin important endpoints from the tree below.": "把重要接口从下方树中固定到这里。",
    "Pinned": "已固定",
    "Recently opened endpoints will appear here.": "最近打开过的接口会出现在这里。",
    "Recent": "最近",
    "Open quick access {name}": "打开快捷入口 {name}",
    "Navigation": "导航",
    "Collapse noise and steer the tree.": "收起噪音，掌控整棵树。",
    "Search keeps matched branches open.": "搜索会保持命中的分支处于展开状态。",
    "Change sort mode, collapse branches, and keep project-scale trees easier to scan.": "切换排序方式、折叠分支，让项目级大树更易扫描。",
    "Modules": "模块",
    "Groups": "分组",
    "Endpoints": "接口",
    "Project order": "项目顺序",
    "A-Z": "A-Z",
    "Method": "方法",
    "Expand all": "全部展开",
    "Collapse all": "全部折叠",
    "Expand": "展开",
    "Collapse": "折叠",
    "module": "模块",
    "group": "分组",
    "{count} groups": "{count} 个分组",
    "{count} endpoints": "{count} 个接口",
    "sidebar.moduleSummary": "{groups} 个分组 · {endpoints} 个接口",
    "tree.endpointCount": "{count} 个接口",
    "tree.groupsAndEndpoints": "{groups} 个分组 / {endpoints} 个接口",
    "tree.moduleBadge": "模块",
    "tree.routeSummary": "{method} {path}",
    "Search mode keeps matching branches open.": "搜索模式会保持命中的分支展开。",
    "The active endpoint branch stays visible while you work.": "当前活跃接口所在分支会在操作时持续可见。",
    "Module {id} name": "模块 {id} 名称",
    "Rename module {id}": "重命名模块 {id}",
    "Rename": "重命名",
    "Delete module {id}": "删除模块 {id}",
    "Delete": "删除",
    "Module collapsed. Expand it to manage groups and endpoints.": "模块已折叠。展开后即可管理分组与接口。",
    "New group name": "新分组名称",
    "Users": "用户",
    "Add group": "添加分组",
    "No groups yet.": "当前还没有分组。",
    "Group {id} name": "分组 {id} 名称",
    "Rename group {id}": "重命名分组 {id}",
    "Delete group {id}": "删除分组 {id}",
    "Group collapsed. Expand it to manage endpoints.": "分组已折叠。展开后即可管理接口。",
    "New endpoint name": "新接口名称",
    "Create User": "创建用户",
    "New endpoint method": "新接口方法",
    "New endpoint path": "新接口路径",
    "Add endpoint": "添加接口",
    "{action} endpoint {id}": "{action} 接口 {id}",
    "Pin": "固定",
    "Unpin": "取消固定",
    "Endpoint {id} name": "接口 {id} 名称",
    "Endpoint {id} path": "接口 {id} 路径",
    "Rename endpoint {id}": "重命名接口 {id}",
    "Rename endpoint": "重命名接口",
    "Delete endpoint {id}": "删除接口 {id}",
    "Delete endpoint": "删除接口",
    "Environments": "环境",
    "Target environments": "目标环境",
    "Manage debug-safe environments, auth presets, and portable workbench bundles.": "统一管理安全可调试的环境、鉴权预设以及可携带的工作台环境包。",
    "Environment Lab": "环境实验室",
    "Portable presets with safer import and cloning.": "更安全的可携带预设、导入与克隆。",
    "Open export bundle": "打开导出包",
    "Open environment import": "打开环境导入",
    "Environment count": "环境数量",
    "Live presets in this workbench": "当前工作台中的可用预设",
    "Active environment": "当前环境",
    "None selected": "未选择",
    "Pick a preset for debug runs": "选择一个预设用于调试运行",
    "Default environment": "默认环境",
    "Not set": "未设置",
    "Imports never replace the default flag": "导入不会覆盖默认环境标记",
    "Export bundle": "导出环境包",
    "Version 1 bundles include headers, query presets, variables, debug rules, and auth settings.": "版本 1 环境包会包含请求头、查询预设、变量、调试规则与鉴权设置。",
    "Read only": "只读",
    "Copy this JSON into another project workbench to seed matching environments.": "把这段 JSON 复制到另一个项目工作台中，即可快速建立同构环境。",
    "Environment bundle export": "环境包导出",
    "Environment bundle import": "环境包导入",
    "Only version 1 bundles are accepted. Imported environments are always created as non-default copies.": "仅接受版本 1 的环境包，导入的环境始终会创建为非默认副本。",
    "Import preview": "导入预览",
    "No bundle loaded": "尚未载入环境包",
    "Every imported environment will land as a non-default copy.": "所有导入环境都会落为非默认副本。",
    "Paste a bundle to validate it before running the batch import.": "先粘贴环境包并完成校验，再执行批量导入。",
    "Importing...": "导入中...",
    "Import environment bundle": "导入环境包",
    "1 environment ready to import": "有 1 个环境可导入",
    "{count} environments ready to import": "有 {count} 个环境可导入",
    "Project Policy": "项目策略",
    "Control which hosts this project can debug against before environment overrides apply.": "在环境级覆盖生效之前，先定义这个项目允许调试访问哪些主机。",
    "Save project debug policy": "保存项目调试策略",
    "New environment": "新环境",
    "Add a reusable target profile": "添加一个可复用的目标配置",
    "New environment name": "新环境名称",
    "New environment base URL": "新环境基础地址",
    "New environment variables": "新环境变量",
    "New environment headers": "新环境请求头",
    "New environment query": "新环境查询参数",
    "New environment auth mode": "新环境鉴权模式",
    "No auth preset": "无鉴权预设",
    "Bearer token": "Bearer 令牌",
    "API key header": "API Key 请求头",
    "API key query parameter": "API Key 查询参数",
    "Basic auth": "Basic 认证",
    "New environment debug host mode": "新环境调试主机模式",
    "Inherit global + project": "继承全局 + 项目规则",
    "Append environment rules": "追加环境规则",
    "Override project rules": "覆盖项目规则",
    "New environment debug rules": "新环境调试规则",
    "Add environment": "添加环境",
    "No environments yet.": "当前还没有环境。",
    "Active": "当前使用",
    "Default": "默认",
    "Use environment": "使用环境",
    "Environment {id}": "环境 {id}",
    "Environment {id} name": "环境 {id} 名称",
    "Environment {id} base URL": "环境 {id} 基础地址",
    "Environment {id} variables": "环境 {id} 变量",
    "Environment {id} headers": "环境 {id} 请求头",
    "Environment {id} query": "环境 {id} 查询参数",
    "Environment {id} auth mode": "环境 {id} 鉴权模式",
    "Environment {id} debug host mode": "环境 {id} 调试主机模式",
    "Clone": "克隆",
    "Save environment": "保存环境",
    "Delete environment": "删除环境",
    "Bearer preset": "Bearer 预设",
    "Header API key": "Header API Key",
    "Query API key": "Query API Key",
    "workbench.tab.debug": "调试",
    "workbench.tab.documentation": "文档",
    "workbench.tab.environments": "环境",
    "workbench.heroEyebrow": "项目工作台",
    "workbench.heroSubtitle": "将文档、运行时调试、环境和协作控制压缩成清晰的多泳道视图。",
    "workbench.badge.writable": "可编辑",
    "workbench.badge.readOnly": "只读",
    "workbench.action.browseDocs": "浏览文档",
    "workbench.action.shareDocs": "分享文档",
    "workbench.action.mockCenter": "Mock 中心",
    "workbench.stats.modules": "模块",
    "workbench.stats.groups": "分组",
    "workbench.stats.endpoints": "接口",
    "workbench.lanesTitle": "工作台泳道",
    "workbench.searchTree": "搜索树",
    "workbench.searchTreePlaceholder": "搜索模块、分组、接口或路径",
    "workbench.tab.members": "成员",
    "workbench.tab.mock": "Mock",
    "workbench.tab.overview": "总览",
    "workbench.overview.eyebrow": "工作台聚焦",
    "workbench.overview.title": "项目节奏一眼掌握",
    "workbench.overview.detail": "用文档泳道处理契约编辑，用 Mock 泳道塑形运行时，用调试泳道发起真实请求，用成员泳道治理协作权限。",
    "workbench.overview.card.documentation.eyebrow": "文档泳道",
    "workbench.overview.card.documentation.title": "{moduleCount} 个模块 · {groupCount} 个分组",
    "workbench.overview.card.documentation.detail": "让接口结构保持紧凑且可检索，而不是在冗长面板里来回滚动。",
    "workbench.overview.card.runtime.eyebrow": "运行时泳道",
    "workbench.overview.card.runtime.title": "{environmentCount} 个环境 · {debugCount} 条调试记录",
    "workbench.overview.card.runtime.detail": "把运行时验证和契约编辑拆开，让每条泳道都更专注。",
    "workbench.overview.card.members.eyebrow": "成员泳道",
    "workbench.overview.card.members.title": "{memberCount} 位协作者 · {adminCount} 个管理员席位",
    "workbench.overview.card.members.detail": "当你需要重新分配角色或检查所有权时，直接进入成员泳道。",
    "workbench.overview.card.mock.eyebrow": "Mock 泳道",
    "workbench.overview.card.mock.title": "{mockCount} 个已发布 Mock 版本",
    "workbench.overview.card.mock.detail": "把草稿规则和已发布运行时拆到独立泳道里，方便随时对照。",
    "workbench.overview.activeEndpoint.eyebrow": "当前接口",
    "workbench.overview.activeEndpoint.emptyTitle": "尚未选择接口",
    "workbench.overview.activeEndpoint.emptyDetail": "打开文档泳道并选择一个接口，即可在这里看到当前聚焦对象。",
    "workbench.documentation.loadingTree": "正在加载项目树...",
    "workbench.documentation.emptySearch": "没有匹配的节点。"
  }
};

type AppPreferencesContextValue = {
  locale: AppLocale;
  resolvedTheme: ResolvedTheme;
  setLocale: (locale: AppLocale) => void;
  setTheme: (theme: ThemePreference) => void;
  t: (key: string, values?: TranslationValues) => string;
  theme: ThemePreference;
};

const defaultContext: AppPreferencesContextValue = {
  locale: "en-US",
  resolvedTheme: "light",
  setLocale: () => undefined,
  setTheme: () => undefined,
  t: (key, values) => formatMessage(key, values, "en-US"),
  theme: "light"
};

const AppPreferencesContext = createContext<AppPreferencesContextValue>(defaultContext);

export function AppPreferencesProvider({ children }: PropsWithChildren) {
  const [locale, setLocale] = useState<AppLocale>("zh-CN");
  const [theme, setTheme] = useState<ThemePreference>("system");
  const [systemTheme, setSystemTheme] = useState<ResolvedTheme>("light");

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    const storedLocale = window.localStorage.getItem(LOCALE_STORAGE_KEY);
    const storedTheme = window.localStorage.getItem(THEME_STORAGE_KEY);

    if (storedLocale === "zh-CN" || storedLocale === "en-US") {
      setLocale(storedLocale);
    }

    if (storedTheme === "system" || storedTheme === "dark" || storedTheme === "light") {
      setTheme(storedTheme);
    }
  }, []);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    if (typeof window.matchMedia !== "function") {
      setSystemTheme("light");
      return;
    }

    const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");

    function syncSystemTheme() {
      setSystemTheme(mediaQuery.matches ? "dark" : "light");
    }

    syncSystemTheme();
    mediaQuery.addEventListener?.("change", syncSystemTheme);

    return () => mediaQuery.removeEventListener?.("change", syncSystemTheme);
  }, []);

  const resolvedTheme = theme === "system" ? systemTheme : theme;

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem(LOCALE_STORAGE_KEY, locale);
    document.documentElement.lang = locale;
  }, [locale]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }

    window.localStorage.setItem(THEME_STORAGE_KEY, theme);
    document.documentElement.dataset.theme = resolvedTheme;
    document.documentElement.style.colorScheme = resolvedTheme;
  }, [resolvedTheme, theme]);

  const value = useMemo<AppPreferencesContextValue>(
    () => ({
      locale,
      resolvedTheme,
      setLocale,
      setTheme,
      t: (key, values) => formatMessage(key, values, locale),
      theme
    }),
    [locale, resolvedTheme, theme]
  );

  return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
}

export function useAppPreferences() {
  return useContext(AppPreferencesContext);
}

export function useI18n() {
  const { locale, t } = useAppPreferences();

  return {
    locale,
    t
  };
}

function formatMessage(key: string, values: TranslationValues | undefined, locale: AppLocale) {
  const catalog = messages[locale];
  const fallbackCatalog = messages["en-US"];
  const pluralKey =
    values?.count !== undefined && Number(values.count) !== 1 && (catalog[`${key}_plural`] || fallbackCatalog[`${key}_plural`])
      ? `${key}_plural`
      : key;
  const template = catalog[pluralKey] ?? fallbackCatalog[pluralKey] ?? key;

  if (!values) {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (_, token: string) => String(values[token] ?? ""));
}
